/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import info5100.university.example.CourseSchedule.CourseOffer;
import info5100.university.example.CourseSchedule.CourseSchedule;
import info5100.university.example.Department.Department;
import info5100.university.example.Info5001UniversityExample;
import info5100.university.example.Persona.StudentDirectory;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Tharoon
 */
public class Professor_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Professor_Frame
     */
        static ArrayList<String> al2 = new ArrayList();
     static StudentDirectory sd;
    public Professor_Frame() {
        initComponents();
      ProfSubpanel.setVisible(false);
      
      
      //ProfLoginPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProfLoginPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Profidlbl = new javax.swing.JLabel();
        Profpasslbl = new javax.swing.JLabel();
        ProfidTxt = new javax.swing.JTextField();
        ProfpassTxt = new javax.swing.JPasswordField();
        profloginbtn = new javax.swing.JButton();
        ProfSubpanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Professor Login");

        Profidlbl.setText("User ID:");

        Profpasslbl.setText("Password:");

        profloginbtn.setText("Login");
        profloginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profloginbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProfLoginPanelLayout = new javax.swing.GroupLayout(ProfLoginPanel);
        ProfLoginPanel.setLayout(ProfLoginPanelLayout);
        ProfLoginPanelLayout.setHorizontalGroup(
            ProfLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfLoginPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ProfLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProfpassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProfidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
            .addGroup(ProfLoginPanelLayout.createSequentialGroup()
                .addGroup(ProfLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfLoginPanelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(ProfLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Profpasslbl)
                            .addComponent(Profidlbl)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ProfLoginPanelLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(profloginbtn)))
                .addGap(80, 118, Short.MAX_VALUE))
        );

        ProfLoginPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ProfidTxt, ProfpassTxt});

        ProfLoginPanelLayout.setVerticalGroup(
            ProfLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfLoginPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(ProfLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Profidlbl)
                    .addComponent(ProfidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(ProfLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Profpasslbl)
                    .addComponent(ProfpassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(profloginbtn)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ProfSubpanelLayout = new javax.swing.GroupLayout(ProfSubpanel);
        ProfSubpanel.setLayout(ProfSubpanelLayout);
        ProfSubpanelLayout.setHorizontalGroup(
            ProfSubpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        ProfSubpanelLayout.setVerticalGroup(
            ProfSubpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProfLoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ProfSubpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProfLoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ProfSubpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profloginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profloginbtnActionPerformed
        // TODO add your handling code here:
        String id=null;
        System.out.println("Mouse clicked");
       
        ProfSubpanel.setVisible(true);
        ProfLoginPanel.setVisible(false);
        id = ProfidTxt.getText();
        System.out.println(getProfessorList("Fall",id));
        JButton[] buttons = new JButton[5];
        for (int i = 0; i < buttons.length; i++) {
                this.getContentPane().setLayout(new FlowLayout());
                    System.out.println("Loop3");
                    buttons[i]=new JButton("hey"+i);
                   add(buttons[i]);
                    //b.setBounds(500, 500, 100, 20);               
                    //ProfSubpanel.add(buttons[i]);
                    
                   

               }
        
            
    }//GEN-LAST:event_profloginbtnActionPerformed

    /**
     * @param args the command line arguments
     */
        public ArrayList getProfessorList(String semester, String id)
    {
        Department department = sd.getDepartment();
        CourseSchedule courseSchedule = department.getCourseSchedule("Fall2020");
       ArrayList<CourseOffer> al1 = courseSchedule.getSchedule();
        System.out.println(al1.size());
                 for(int i=0 ; i < al1.size(); i++){
            //System.out.println(al1.get(i).getFacultyProfile());
            if(al1.get(i).getFacultyProfile().getPerson().getPersonId().equals(id)){
                al2.add(al1.get(i).getCourse().getCOurseNumber());
            }
        }
                 return al1;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Professor_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Professor_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Professor_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Professor_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                System.out.println("Frame");
                new Professor_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ProfLoginPanel;
    private javax.swing.JPanel ProfSubpanel;
    private javax.swing.JTextField ProfidTxt;
    private javax.swing.JLabel Profidlbl;
    private javax.swing.JPasswordField ProfpassTxt;
    private javax.swing.JLabel Profpasslbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton profloginbtn;
    // End of variables declaration//GEN-END:variables
}
