/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI;
import TestData.TestData;
import helper.Helper;
import info5100.university.example.CourseCatalog.Course;
import info5100.university.example.CourseSchedule.CourseOffer;
import info5100.university.example.Department.Department;
import info5100.university.example.Department.DepartmentDirectory;
import info5100.university.example.Info5001UniversityExample;

import info5100.university.example.Persona.Faculty.FacultyProfile;

import info5100.university.example.Persona.Faculty.Alumni.Alumni;

import info5100.university.example.Persona.StudentProfile;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shreyascr
 */
public class univAdmin extends javax.swing.JPanel {
     HashMap<String, Department> map = new HashMap();
            TestData testData = TestData.getInstance();
            DepartmentDirectory department = testData.getDd();
            ArrayList<Department> departmentlist = department.getDd();
            HashMap<String, CourseOffer> coursemap = new HashMap();
            String depName;
            String depNameProf;

    /** Creates new form univAdmin */
    public univAdmin() {
        initComponents();
        testData.test2();
         UnvTbPane.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        StudentLoginPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        UsernameTextField = new javax.swing.JTextField();
        UsernameLabel = new javax.swing.JLabel();
        PasswordLowerPanel = new javax.swing.JPanel();
        PasswordField = new javax.swing.JPasswordField();
        UsernameLowerPanel = new javax.swing.JPanel();
        LoginButton = new javax.swing.JButton();
        UnvTbPane = new javax.swing.JPanel();
        InUnvTabPane = new javax.swing.JTabbedPane();
        ShwCrPnl = new javax.swing.JPanel();
        CrLstDeptLbl = new javax.swing.JLabel();
        CrDptComboBox = new javax.swing.JComboBox<>();
        CrLstPnl = new javax.swing.JPanel();
        CrNameScrPnl = new javax.swing.JScrollPane();
        CrNameTable = new javax.swing.JTable();
        ShStdPnl = new javax.swing.JPanel();
        StdLstDeptLbl = new javax.swing.JLabel();
        StdDptComboBox = new javax.swing.JComboBox<>();
        StdLstPnl = new javax.swing.JPanel();
        StdNameScrPnl = new javax.swing.JScrollPane();
        StdNameTable = new javax.swing.JTable();
        Addstupanel = new javax.swing.JPanel();
        AddstudeptLbl = new javax.swing.JLabel();
        AddstucouLbl = new javax.swing.JLabel();
        AddstuNameLbl = new javax.swing.JLabel();
        AddStuIdLbl = new javax.swing.JLabel();
        AddStuDeptcb = new javax.swing.JComboBox<>();
        Addstucoucom = new javax.swing.JComboBox<>();
        AddstunameTxt = new javax.swing.JTextField();
        AddstuIdTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        AddStudent = new javax.swing.JButton();
        AddProfPanel = new javax.swing.JPanel();
        AddstudeptLbl1 = new javax.swing.JLabel();
        AddstucouLbl1 = new javax.swing.JLabel();
        AddstuNameLbl1 = new javax.swing.JLabel();
        AddStuIdLbl1 = new javax.swing.JLabel();
        AddProfDeptcb1 = new javax.swing.JComboBox<>();
        AddProfcoucom = new javax.swing.JComboBox<>();
        AddProfnameTxt = new javax.swing.JTextField();
        AddProfIdTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        AddProf = new javax.swing.JButton();
        ShAlmn = new javax.swing.JPanel();
        AlmnLstDeptLbl = new javax.swing.JLabel();
        AlmnDptComboBox = new javax.swing.JComboBox<>();
        AlmnLstPnl = new javax.swing.JPanel();
        AlmnNameScrPnl = new javax.swing.JScrollPane();
        AlmnNameTable = new javax.swing.JTable();
        ShAyPnl = new javax.swing.JPanel();
        AyLstDeptLbl = new javax.swing.JLabel();
        AyDptComboBox = new javax.swing.JComboBox<>();
        AyCrRkPnl = new javax.swing.JPanel();
        AyCrRkScrlPnl = new javax.swing.JScrollPane();
        AyCrRkTable = new javax.swing.JTable();
        AyFcRkPnl = new javax.swing.JPanel();
        AyFkRkScrlPnl = new javax.swing.JScrollPane();
        AyFkRkTable = new javax.swing.JTable();
        FcRkLbl = new javax.swing.JLabel();
        CrRkLbl = new javax.swing.JLabel();
        CrScMtrxLbl = new javax.swing.JLabel();
        CrScMtrxValLbl = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(29, 44, 64));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 0));

        StudentLoginPanel.setBackground(new java.awt.Color(23, 35, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMIN LOG IN");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout StudentLoginPanelLayout = new javax.swing.GroupLayout(StudentLoginPanel);
        StudentLoginPanel.setLayout(StudentLoginPanelLayout);
        StudentLoginPanelLayout.setHorizontalGroup(
            StudentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        StudentLoginPanelLayout.setVerticalGroup(
            StudentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        PasswordLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(153, 153, 153));
        PasswordLabel.setText("PASSWORD:");

        UsernameTextField.setBackground(new java.awt.Color(44, 63, 87));
        UsernameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UsernameTextField.setForeground(new java.awt.Color(153, 153, 153));
        UsernameTextField.setBorder(null);
        UsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextFieldActionPerformed(evt);
            }
        });

        UsernameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UsernameLabel.setForeground(new java.awt.Color(153, 153, 153));
        UsernameLabel.setText("USERNAME: ");

        PasswordLowerPanel.setBackground(new java.awt.Color(255, 153, 153));
        PasswordLowerPanel.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout PasswordLowerPanelLayout = new javax.swing.GroupLayout(PasswordLowerPanel);
        PasswordLowerPanel.setLayout(PasswordLowerPanelLayout);
        PasswordLowerPanelLayout.setHorizontalGroup(
            PasswordLowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PasswordLowerPanelLayout.setVerticalGroup(
            PasswordLowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        PasswordField.setBackground(new java.awt.Color(44, 63, 87));
        PasswordField.setBorder(null);
        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });

        UsernameLowerPanel.setBackground(new java.awt.Color(255, 153, 153));
        UsernameLowerPanel.setForeground(new java.awt.Color(255, 153, 153));
        UsernameLowerPanel.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout UsernameLowerPanelLayout = new javax.swing.GroupLayout(UsernameLowerPanel);
        UsernameLowerPanel.setLayout(UsernameLowerPanelLayout);
        UsernameLowerPanelLayout.setHorizontalGroup(
            UsernameLowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        UsernameLowerPanelLayout.setVerticalGroup(
            UsernameLowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        LoginButton.setBackground(new java.awt.Color(44, 63, 87));
        LoginButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(153, 153, 153));
        LoginButton.setText("LOGIN");
        LoginButton.setBorder(null);
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StudentLoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(PasswordLowerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1172, Short.MAX_VALUE)
                    .addComponent(PasswordField)
                    .addComponent(UsernameLowerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1172, Short.MAX_VALUE)
                    .addComponent(UsernameTextField)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(PasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(UsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 975, Short.MAX_VALUE)))
                .addContainerGap(147, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(686, 686, 686))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(StudentLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(UsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(UsernameLowerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(PasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PasswordLowerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(625, Short.MAX_VALUE))
        );

        InUnvTabPane.setBackground(new java.awt.Color(29, 44, 64));
        InUnvTabPane.setForeground(new java.awt.Color(153, 153, 153));
        InUnvTabPane.setPreferredSize(new java.awt.Dimension(1420, 1000));

        ShwCrPnl.setBackground(new java.awt.Color(29, 44, 64));
        ShwCrPnl.setForeground(new java.awt.Color(153, 153, 153));

        CrLstDeptLbl.setForeground(new java.awt.Color(153, 153, 153));
        CrLstDeptLbl.setText("Select Department");

        CrDptComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Option" }));
        CrDptComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrDptComboBoxActionPerformed(evt);
            }
        });

        CrNameTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Course Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CrNameScrPnl.setViewportView(CrNameTable);

        javax.swing.GroupLayout CrLstPnlLayout = new javax.swing.GroupLayout(CrLstPnl);
        CrLstPnl.setLayout(CrLstPnlLayout);
        CrLstPnlLayout.setHorizontalGroup(
            CrLstPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrLstPnlLayout.createSequentialGroup()
                .addComponent(CrNameScrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CrLstPnlLayout.setVerticalGroup(
            CrLstPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrLstPnlLayout.createSequentialGroup()
                .addComponent(CrNameScrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ShwCrPnlLayout = new javax.swing.GroupLayout(ShwCrPnl);
        ShwCrPnl.setLayout(ShwCrPnlLayout);
        ShwCrPnlLayout.setHorizontalGroup(
            ShwCrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShwCrPnlLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(ShwCrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ShwCrPnlLayout.createSequentialGroup()
                        .addComponent(CrLstDeptLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CrDptComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CrLstPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(804, Short.MAX_VALUE))
        );
        ShwCrPnlLayout.setVerticalGroup(
            ShwCrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShwCrPnlLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(ShwCrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CrLstDeptLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CrDptComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(CrLstPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(667, Short.MAX_VALUE))
        );

        InUnvTabPane.addTab("Course List", ShwCrPnl);

        ShStdPnl.setBackground(new java.awt.Color(29, 44, 64));

        StdLstDeptLbl.setForeground(new java.awt.Color(153, 153, 153));
        StdLstDeptLbl.setText("Select Department");

        StdDptComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Option" }));
        StdDptComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StdDptComboBoxActionPerformed(evt);
            }
        });

        StdNameTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Student Name", "Stduent GPA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        StdNameScrPnl.setViewportView(StdNameTable);

        javax.swing.GroupLayout StdLstPnlLayout = new javax.swing.GroupLayout(StdLstPnl);
        StdLstPnl.setLayout(StdLstPnlLayout);
        StdLstPnlLayout.setHorizontalGroup(
            StdLstPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StdLstPnlLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(StdNameScrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        StdLstPnlLayout.setVerticalGroup(
            StdLstPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StdLstPnlLayout.createSequentialGroup()
                .addComponent(StdNameScrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ShStdPnlLayout = new javax.swing.GroupLayout(ShStdPnl);
        ShStdPnl.setLayout(ShStdPnlLayout);
        ShStdPnlLayout.setHorizontalGroup(
            ShStdPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShStdPnlLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(ShStdPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ShStdPnlLayout.createSequentialGroup()
                        .addComponent(StdLstDeptLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StdDptComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(StdLstPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(855, Short.MAX_VALUE))
        );
        ShStdPnlLayout.setVerticalGroup(
            ShStdPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShStdPnlLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(ShStdPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StdLstDeptLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StdDptComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(StdLstPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(658, Short.MAX_VALUE))
        );

        InUnvTabPane.addTab("Student List", ShStdPnl);

        Addstupanel.setBackground(new java.awt.Color(29, 44, 64));

        AddstudeptLbl.setForeground(new java.awt.Color(153, 153, 153));
        AddstudeptLbl.setText("Department:");

        AddstucouLbl.setForeground(new java.awt.Color(153, 153, 153));
        AddstucouLbl.setText("Course:");

        AddstuNameLbl.setForeground(new java.awt.Color(153, 153, 153));
        AddstuNameLbl.setText("Name:");

        AddStuIdLbl.setForeground(new java.awt.Color(153, 153, 153));
        AddStuIdLbl.setText("Id:");

        AddStuDeptcb.setBackground(new java.awt.Color(44, 63, 87));
        AddStuDeptcb.setForeground(new java.awt.Color(153, 153, 153));
        AddStuDeptcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department" }));
        AddStuDeptcb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddStuDeptcbMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AddStuDeptcbMousePressed(evt);
            }
        });
        AddStuDeptcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStuDeptcbActionPerformed(evt);
            }
        });

        Addstucoucom.setBackground(new java.awt.Color(44, 63, 87));
        Addstucoucom.setForeground(new java.awt.Color(153, 153, 153));
        Addstucoucom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Course" }));
        Addstucoucom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddstucoucomActionPerformed(evt);
            }
        });

        AddstunameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddstunameTxtActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ADD STUDENT");

        AddStudent.setBackground(new java.awt.Color(44, 63, 87));
        AddStudent.setForeground(new java.awt.Color(153, 153, 153));
        AddStudent.setText("Add");
        AddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddstupanelLayout = new javax.swing.GroupLayout(Addstupanel);
        Addstupanel.setLayout(AddstupanelLayout);
        AddstupanelLayout.setHorizontalGroup(
            AddstupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddstupanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddstupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddstuNameLbl)
                    .addComponent(AddStuIdLbl)
                    .addComponent(AddstudeptLbl)
                    .addComponent(AddstucouLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 519, Short.MAX_VALUE)
                .addGroup(AddstupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddstupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(AddstunameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                        .addComponent(AddstuIdTxt)
                        .addComponent(AddStuDeptcb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Addstucoucom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(339, 339, 339))
            .addGroup(AddstupanelLayout.createSequentialGroup()
                .addGroup(AddstupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddstupanelLayout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddstupanelLayout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(AddStudent)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddstupanelLayout.setVerticalGroup(
            AddstupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddstupanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel5)
                .addGap(34, 34, 34)
                .addGroup(AddstupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddstuNameLbl)
                    .addGroup(AddstupanelLayout.createSequentialGroup()
                        .addComponent(AddstunameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AddstupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddStuIdLbl)
                            .addComponent(AddstuIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addGroup(AddstupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddstudeptLbl)
                    .addComponent(AddStuDeptcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(AddstupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddstucouLbl)
                    .addComponent(Addstucoucom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AddStudent)
                .addContainerGap(667, Short.MAX_VALUE))
        );

        InUnvTabPane.addTab("Add Student", Addstupanel);

        AddProfPanel.setBackground(new java.awt.Color(29, 44, 64));
        AddProfPanel.setForeground(new java.awt.Color(153, 153, 153));

        AddstudeptLbl1.setForeground(new java.awt.Color(153, 153, 153));
        AddstudeptLbl1.setText("Department:");

        AddstucouLbl1.setForeground(new java.awt.Color(153, 153, 153));
        AddstucouLbl1.setText("Course:");

        AddstuNameLbl1.setForeground(new java.awt.Color(153, 153, 153));
        AddstuNameLbl1.setText("Name:");

        AddStuIdLbl1.setForeground(new java.awt.Color(153, 153, 153));
        AddStuIdLbl1.setText("Id:");

        AddProfDeptcb1.setBackground(new java.awt.Color(44, 63, 87));
        AddProfDeptcb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department" }));
        AddProfDeptcb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddProfDeptcb1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AddProfDeptcb1MousePressed(evt);
            }
        });
        AddProfDeptcb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProfDeptcb1ActionPerformed(evt);
            }
        });

        AddProfcoucom.setBackground(new java.awt.Color(44, 63, 87));
        AddProfcoucom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Course" }));
        AddProfcoucom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProfcoucomActionPerformed(evt);
            }
        });

        AddProfnameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProfnameTxtActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ADD PROFESSOR");

        AddProf.setBackground(new java.awt.Color(44, 63, 86));
        AddProf.setForeground(new java.awt.Color(153, 153, 153));
        AddProf.setText("Add");
        AddProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddProfPanelLayout = new javax.swing.GroupLayout(AddProfPanel);
        AddProfPanel.setLayout(AddProfPanelLayout);
        AddProfPanelLayout.setHorizontalGroup(
            AddProfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddProfPanelLayout.createSequentialGroup()
                .addGroup(AddProfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddProfPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(AddProfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddstuNameLbl1)
                            .addComponent(AddStuIdLbl1)
                            .addComponent(AddstudeptLbl1)
                            .addComponent(AddstucouLbl1))
                        .addGap(341, 341, 341)
                        .addGroup(AddProfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(AddProfDeptcb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddProfIdTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                            .addComponent(AddProfcoucom, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddProfnameTxt)))
                    .addGroup(AddProfPanelLayout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddProfPanelLayout.createSequentialGroup()
                        .addGap(385, 385, 385)
                        .addComponent(AddProf)))
                .addContainerGap(517, Short.MAX_VALUE))
        );
        AddProfPanelLayout.setVerticalGroup(
            AddProfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddProfPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel6)
                .addGap(31, 31, 31)
                .addGroup(AddProfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AddProfPanelLayout.createSequentialGroup()
                        .addGroup(AddProfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AddstuNameLbl1)
                            .addGroup(AddProfPanelLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(AddProfnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(AddProfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AddStuIdLbl1)
                                    .addComponent(AddProfIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(29, 29, 29)
                        .addGroup(AddProfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddstudeptLbl1)
                            .addComponent(AddProfDeptcb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(AddstucouLbl1))
                    .addComponent(AddProfcoucom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(AddProf)
                .addContainerGap(683, Short.MAX_VALUE))
        );

        InUnvTabPane.addTab("Add Professor", AddProfPanel);

        ShAlmn.setBackground(new java.awt.Color(29, 44, 64));

        AlmnLstDeptLbl.setForeground(new java.awt.Color(153, 153, 153));
        AlmnLstDeptLbl.setText("Select Department");

        AlmnDptComboBox.setBackground(new java.awt.Color(44, 63, 87));
        AlmnDptComboBox.setForeground(new java.awt.Color(153, 153, 153));
        AlmnDptComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Option" }));
        AlmnDptComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlmnDptComboBoxActionPerformed(evt);
            }
        });

        AlmnNameTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Alumini Name", "Promotions", "Salary Range", "Gradutation Year", "Position"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        AlmnNameTable.setPreferredSize(new java.awt.Dimension(600, 64));
        AlmnNameScrPnl.setViewportView(AlmnNameTable);

        javax.swing.GroupLayout AlmnLstPnlLayout = new javax.swing.GroupLayout(AlmnLstPnl);
        AlmnLstPnl.setLayout(AlmnLstPnlLayout);
        AlmnLstPnlLayout.setHorizontalGroup(
            AlmnLstPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AlmnLstPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AlmnNameScrPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE))
        );
        AlmnLstPnlLayout.setVerticalGroup(
            AlmnLstPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AlmnNameScrPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ShAlmnLayout = new javax.swing.GroupLayout(ShAlmn);
        ShAlmn.setLayout(ShAlmnLayout);
        ShAlmnLayout.setHorizontalGroup(
            ShAlmnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShAlmnLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(ShAlmnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ShAlmnLayout.createSequentialGroup()
                        .addComponent(AlmnLstDeptLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AlmnDptComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AlmnLstPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(986, Short.MAX_VALUE))
        );
        ShAlmnLayout.setVerticalGroup(
            ShAlmnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShAlmnLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(ShAlmnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlmnLstDeptLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AlmnDptComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(AlmnLstPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(695, Short.MAX_VALUE))
        );

        InUnvTabPane.addTab("Alumini Details", ShAlmn);

        ShAyPnl.setBackground(new java.awt.Color(29, 44, 66));
        ShAyPnl.setForeground(new java.awt.Color(153, 153, 153));

        AyLstDeptLbl.setForeground(new java.awt.Color(153, 153, 153));
        AyLstDeptLbl.setText("Select Department");

        AyDptComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Option" }));
        AyDptComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AyDptComboBoxActionPerformed(evt);
            }
        });

        AyCrRkTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Course Ranking", "Course Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        AyCrRkScrlPnl.setViewportView(AyCrRkTable);

        javax.swing.GroupLayout AyCrRkPnlLayout = new javax.swing.GroupLayout(AyCrRkPnl);
        AyCrRkPnl.setLayout(AyCrRkPnlLayout);
        AyCrRkPnlLayout.setHorizontalGroup(
            AyCrRkPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AyCrRkPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AyCrRkScrlPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AyCrRkPnlLayout.setVerticalGroup(
            AyCrRkPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AyCrRkPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AyCrRkScrlPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        AyFkRkTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Faculty Ranking", "Faculty Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        AyFkRkScrlPnl.setViewportView(AyFkRkTable);

        javax.swing.GroupLayout AyFcRkPnlLayout = new javax.swing.GroupLayout(AyFcRkPnl);
        AyFcRkPnl.setLayout(AyFcRkPnlLayout);
        AyFcRkPnlLayout.setHorizontalGroup(
            AyFcRkPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AyFcRkPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AyFkRkScrlPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AyFcRkPnlLayout.setVerticalGroup(
            AyFcRkPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AyFcRkPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AyFkRkScrlPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        FcRkLbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        FcRkLbl.setForeground(new java.awt.Color(255, 255, 255));
        FcRkLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FcRkLbl.setText("Faculty Ranking");

        CrRkLbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CrRkLbl.setForeground(new java.awt.Color(255, 255, 255));
        CrRkLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CrRkLbl.setText("Course Ranking");

        CrScMtrxLbl.setForeground(new java.awt.Color(255, 255, 255));
        CrScMtrxLbl.setText("Carrer Success Metrics");

        CrScMtrxValLbl.setForeground(new java.awt.Color(255, 255, 255));
        CrScMtrxValLbl.setText("Value");

        javax.swing.GroupLayout ShAyPnlLayout = new javax.swing.GroupLayout(ShAyPnl);
        ShAyPnl.setLayout(ShAyPnlLayout);
        ShAyPnlLayout.setHorizontalGroup(
            ShAyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShAyPnlLayout.createSequentialGroup()
                .addGroup(ShAyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ShAyPnlLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(AyLstDeptLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(AyDptComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ShAyPnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ShAyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FcRkLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AyFcRkPnl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(ShAyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AyCrRkPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CrRkLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ShAyPnlLayout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(CrScMtrxValLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(734, Short.MAX_VALUE))
            .addGroup(ShAyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ShAyPnlLayout.createSequentialGroup()
                    .addGap(93, 93, 93)
                    .addComponent(CrScMtrxLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1146, Short.MAX_VALUE)))
        );
        ShAyPnlLayout.setVerticalGroup(
            ShAyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShAyPnlLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(ShAyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AyLstDeptLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AyDptComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ShAyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ShAyPnlLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(FcRkLbl)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ShAyPnlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CrRkLbl)
                        .addGap(18, 18, 18)))
                .addGroup(ShAyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AyFcRkPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AyCrRkPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(CrScMtrxValLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(584, Short.MAX_VALUE))
            .addGroup(ShAyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ShAyPnlLayout.createSequentialGroup()
                    .addGap(362, 362, 362)
                    .addComponent(CrScMtrxLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(583, Short.MAX_VALUE)))
        );

        InUnvTabPane.addTab("Analysis", ShAyPnl);

        javax.swing.GroupLayout UnvTbPaneLayout = new javax.swing.GroupLayout(UnvTbPane);
        UnvTbPane.setLayout(UnvTbPaneLayout);
        UnvTbPaneLayout.setHorizontalGroup(
            UnvTbPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InUnvTabPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1436, Short.MAX_VALUE)
        );
        UnvTbPaneLayout.setVerticalGroup(
            UnvTbPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InUnvTabPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1448, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1429, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(UnvTbPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1031, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(UnvTbPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextFieldActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        jPanel1.setVisible(false);
        UnvTbPane.setVisible(true);
           
            CrLstPnl.setVisible(false);
            StdLstPnl.setVisible(false);
            AlmnLstPnl.setVisible(false);
            AyFcRkPnl.setVisible(false);
            AyCrRkPnl.setVisible(false);
            FcRkLbl.setVisible(false);
            CrRkLbl.setVisible(false);
            CrScMtrxValLbl.setVisible(false);
            CrScMtrxLbl.setVisible(false);
            ArrayList<Department> departmentlist = department.getDd();
            
            for(Department d : departmentlist){
               
                map.put(d.getName(), d);
            }

            for (String name : map.keySet())  
                   CrDptComboBox.addItem(name);
            for (String name : map.keySet()) 
                StdDptComboBox.addItem(name);
            for (String name : map.keySet())  
                   AddStuDeptcb.addItem(name);
            for (String name : map.keySet())  
                   AddProfDeptcb1.addItem(name);
            for (String name : map.keySet())  
                   AlmnDptComboBox.addItem(name);
            for (String name : map.keySet())  
                   AyDptComboBox.addItem(name);
        
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void CrDptComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrDptComboBoxActionPerformed
        // TODO add your handling code here:

        CrLstPnl.setVisible(false);
        StdLstPnl.setVisible(false);
        String selval = CrDptComboBox.getSelectedItem().toString();
        //jTextField1.setText(selval);

        if(selval.equals("Information Systems"))
        {
            CrLstPnl.setVisible(true);
            DefaultTableModel model = (DefaultTableModel) CrNameTable.getModel();
            model.setRowCount(0);

            //System.out.println("Test "+ map.get("Information Systems"));
            List<CourseOffer> co = getCourseOfferedByDepartment(map.get("Information Systems"));

            for(int i=0;i<co.size();i++)

            {
                Object[] row= new Object[1];
                row[0]=co.get(i).getCourse().getName();
                model.addRow(row);

            }
        }
        if(selval.equals("Computer Science"))
        {
            CrLstPnl.setVisible(true);
            DefaultTableModel model = (DefaultTableModel) CrNameTable.getModel();
            model.setRowCount(0);

            //System.out.println("Test "+ map.get("Computer Science"));
            List<CourseOffer> co = getCourseOfferedByDepartment(map.get("Computer Science"));
            for(int i=0;i<co.size();i++)
            //for(CourseOffer c: co)
            {
                Object[] row= new Object[1];
                row[0]=co.get(i).getCourse().getName();
                model.addRow(row);

            }
        }

    }//GEN-LAST:event_CrDptComboBoxActionPerformed

    
    
    public ArrayList<Course> rankCourseByDepartment(Department d){
        
        ArrayList<Course> course = d.getCourseCatalog().getCourseList();
        for(Course c : course)
            System.out.println("BEfore Sorted form course"+ c);
        Collections.sort(course,new Comparator<Course>() {
            @Override
            public int compare(Course o1, Course o2) {
               
                return (o2.getRating()) - (o1.getRating());
            }
        } );
        for(Course c : course)
            System.out.println("Sorted form course"+ c); 
        return course;
        
    }
            
    public ArrayList<FacultyProfile> rankProfessorByDepartment(Department d){
        
        ArrayList<FacultyProfile> fp = d.getFacultyDirectory().getTeacherlist();
        for(FacultyProfile f : fp)
            System.out.println("BEfore Sorted form "+ f);
        Collections.sort(fp,new Comparator<FacultyProfile>() {
            @Override
            public int compare(FacultyProfile o1, FacultyProfile o2) {
               
                return o1.getFacultyRatings() - o2.getFacultyRatings();
            }
        } );
        for(FacultyProfile f : fp)
            System.out.println("Sorted form "+ f);

        return fp;
        
    }
    
    public Double careerSuccesMetricRank(Department d){
        System.out.println(d.getName());
        ArrayList<Alumni> al = d.getAlumniDirectory().getAd();
        int size = al.size();
          System.out.println(" s ss"+ al);
        Double res =0.0;
        for(Alumni a : al){
            System.out.println("BEfore Sorted form "+ a.toString());
            res += a.getCareerSuccess();
        }
        res = res/size;
        
        return res;
        
    }
        public void getDepartmentList(){
         
//        ArrayList<Department> departmentlist = department.getDd();
        for(Department d : departmentlist)
        {
            System.out.println(d.getName());
//            Helper helper = new Helper();
//            List<Course> course = helper.getCourseOffer(d, "Fall2020");
//            for(Course c : course)
//            {
//                System.out.println(c.getName());
//            }
//            List<Person> list = helper.getStudent(d);
//            for(Person p : list)
//            {
//                System.out.println(p.getPersonId());
//            }
            
           
           getCourseOfferedByDepartment(d); 
    }
    
        
        
//        String d1 ="Information Systems";
//        String course ="app eng";
//       
//        for(Department d : departmentlist)
//        {
//            //System.out.println(d.getName());
//            Helper helper = new Helper();
//            List<CourseOffer> course1 = helper.getCourseOfferList(d, "Fall2020");
//            for(CourseOffer c : course1)
//            {
//                    if(c.getCourse().getName().equals(course))
//                    {
//                        helper.addStudent(d, "test", "1234", "Fall2020",c );
//                        
//                    }
//            }
//        }
//        for(Department d : departmentlist)
//        {
//            System.out.println(d.getName());
//            Helper helper = new Helper();
//            List<Course> course2 = helper.getCourseOffer(d, "Fall2020");
//            for(Course c : course2)
//            {
//                System.out.println(c.getName());
//            }
//            List<Person> list = helper.getStudent(d);
//            for(Person p : list)
//            {
//                System.out.println(p.getPersonId());
//            }
//        }
            
            
            
        
        
      //  System.out.println("DD "+ uni.getDd().toString());
//        ArrayList<DepartmentDirectory> d = uni.getDd();
        
    }                                        


    public List<StudentProfile> getStudentsByDepartmentName(Department dpt){
            Helper helper = new Helper();
            List<StudentProfile> p = helper.getStudent(dpt);
//            for(Course c : course)
//            {
//                System.out.println(c.getName());
//            }
//            List<Person> list = helper.getStudent(d);
//            for(Person p : list)
//            {
//                System.out.println(p.getPersonId());
//            }
          //  System.out.println("PP "+ p.get(0).getPersonId());
            return p;
    }
    
    public List<CourseOffer> getCourseOfferedByDepartment(Department d){
        return new Helper().getCourseOfferList(d, "Fall2020");
    }
        public List<Alumni> addaluminiDepartment(Department d){
        return new Helper().getAlumniByDepartment(d);
    }
    public void addStudent(Department d, String sname, String sid, String sem, CourseOffer co){
        
        new Helper().addStudent(d, sname, sid, sem, co);
        
        
    }
   // System.out.println("Std"+new Helper().addStudent(d, "MM", "101", "2", co));
    
    public void addProf(Department d, String profName, String pid, String sem, CourseOffer co){
        
        new Helper().addProfessor(d, profName, pid, sem, co);
    }
    
    private void StdDptComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StdDptComboBoxActionPerformed
        // TODO add your handling code here:

        StdLstPnl.setVisible(false);
        AlmnLstPnl.setVisible(false);
        String selval = StdDptComboBox.getSelectedItem().toString();
        //jTextField1.setText(selval);

        if(selval.equals("Information Systems"))
        {
            StdLstPnl.setVisible(true);
            DefaultTableModel model = (DefaultTableModel) StdNameTable.getModel();
            model.setRowCount(0);

            //System.out.println("Test "+ map.get("Information Systems"));
            //List<CourseOffer> co = getCourseOfferedByDepartment(map.get("Information Systems"));
            List<StudentProfile> p = getStudentsByDepartmentName(map.get("Information Systems"));
            for(int i=0;i<p.size();i++)
            //for(CourseOffer c: co)
            {
                Object[] row= new Object[2];
                //row[0]=co.get(i).getCourse().getName().toString();
                row[0]=p.get(i).getPerson().getPersonId();
                row[1]=p.get(i).getGpa();
                model.addRow(row);
            }

        }

        if(selval.equals("Computer Science"))
        {
            StdLstPnl.setVisible(true);
            DefaultTableModel model = (DefaultTableModel) StdNameTable.getModel();
            model.setRowCount(0);

            System.out.println("Test "+ map.get("Computer Science"));
            //List<CourseOffer> co = getCourseOfferedByDepartment(map.get("Computer Science"));
            List<StudentProfile> p = getStudentsByDepartmentName(map.get("Computer Science"));
            for(int i=0;i<p.size();i++)
            //for(CourseOffer c: co)
            {
                Object[] row= new Object[2];

                row[0]=p.get(i).getPerson().getPersonId();
                row[1]=p.get(i).getGpa();
                model.addRow(row);

            }
        }
    }//GEN-LAST:event_StdDptComboBoxActionPerformed

    private void AddStuDeptcbMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddStuDeptcbMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddStuDeptcbMousePressed

    private void AddStuDeptcbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddStuDeptcbMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AddStuDeptcbMouseClicked

    private void AddStuDeptcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStuDeptcbActionPerformed
        // TODO add your handling code here:
        //getDepartmentList();
        depName = AddStuDeptcb.getSelectedItem().toString();
        System.out.println(depName);
        AddstucoucomActionPerformed(evt);
        //                    List<CourseOffer> depname = getCourseOfferedByDepartment(map.get(depName));
        //        for(CourseOffer co : depname){
            //                        coursemap.put(co.getCourseNumber(), co);
            //              }
        //            for (String couname : coursemap.keySet())
        //                   Addstucoucom.addItem(couname);
    }//GEN-LAST:event_AddStuDeptcbActionPerformed

    private void AddstucoucomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddstucoucomActionPerformed
        // TODO add your handling code here:
        //String courseName =
        List<CourseOffer> depname = getCourseOfferedByDepartment(map.get(depName));
        for(CourseOffer co : depname){
            coursemap.put(co.getCourseNumber(), co);
        }
        for (String couname : coursemap.keySet())
        Addstucoucom.addItem(couname);
    }//GEN-LAST:event_AddstucoucomActionPerformed

    private void AddstunameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddstunameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddstunameTxtActionPerformed

    private void AddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudentActionPerformed
        // TODO add your handling code here:
        depName = AddStuDeptcb.getSelectedItem().toString();
        String stuname=AddstunameTxt.getText();
        String stid = AddstuIdTxt.getText();
        String coursename = Addstucoucom.getSelectedItem().toString();
        addStudent(map.get(depName), stuname, stid, "Fall2020 ", coursemap.get(coursename));
        JOptionPane.showMessageDialog(this,"Student Added");
        InUnvTabPane.setSelectedComponent(this.ShStdPnl);
    }//GEN-LAST:event_AddStudentActionPerformed

    private void AddProfDeptcb1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddProfDeptcb1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddProfDeptcb1MousePressed

    private void AddProfDeptcb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddProfDeptcb1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AddProfDeptcb1MouseClicked

    private void AddProfDeptcb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProfDeptcb1ActionPerformed
        // TODO add your handling code here:
        depNameProf = AddProfDeptcb1.getSelectedItem().toString();
        System.out.println(depNameProf);
        AddProfcoucomActionPerformed(evt);
    }//GEN-LAST:event_AddProfDeptcb1ActionPerformed

    private void AddProfcoucomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProfcoucomActionPerformed
        // TODO add your handling code here:
        List<CourseOffer> depname = getCourseOfferedByDepartment(map.get(depNameProf));
        for(CourseOffer co : depname){
            coursemap.put(co.getCourseNumber(), co);
        }
        for (String couname : coursemap.keySet())
        AddProfcoucom.addItem(couname);
    }//GEN-LAST:event_AddProfcoucomActionPerformed

    private void AddProfnameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProfnameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddProfnameTxtActionPerformed

    private void AddProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProfActionPerformed
        // TODO add your handling code here:
        String profname=AddProfnameTxt.getText();
        String profid = AddProfIdTxt.getText();
        String coursename = AddProfcoucom.getSelectedItem().toString();
        addProf(map.get(depNameProf), profname, profid, "Fall2020 ", coursemap.get(coursename));
        JOptionPane.showMessageDialog(this,"Professor Added");
    }//GEN-LAST:event_AddProfActionPerformed

    private void AlmnDptComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlmnDptComboBoxActionPerformed
        // TODO add your handling code here:
        AlmnLstPnl.setVisible(false);
        StdLstPnl.setVisible(false);
        CrLstPnl.setVisible(false);

        String selval = AlmnDptComboBox.getSelectedItem().toString();
       
        if(selval.equals("Information Systems"))
        {
            AlmnLstPnl.setVisible(true);
            DefaultTableModel model = (DefaultTableModel) AlmnNameTable.getModel();
            model.setRowCount(0);
            List<Alumni> al = addaluminiDepartment(map.get("Information Systems"));
            System.out.println("ID"+al.get(0).getStudentProfile().getPerson().getPersonId());
            for(int i=0;i<al.size();i++)

            {
                Object[] row= new Object[5];
                row[0]=al.get(i).getStudentProfile().getPerson().getPersonId();
                row[1]=al.get(i).getPromotions();
                row[2]=al.get(i).getSalaryRange();
                row[3]=al.get(i).getGradutationYear();
                row[4]=al.get(i).getPosition();
                model.addRow(row);
            } 
            
        }
        
        else if(selval.equals("Computer Science"))
        {
            AlmnLstPnl.setVisible(true);
            DefaultTableModel model = (DefaultTableModel) AlmnNameTable.getModel();
            model.setRowCount(0);

           // System.out.println("Test "+ map.get("Computer Science"));
            List<Alumni> al = addaluminiDepartment(map.get("Computer Science"));
            for(int i=0;i<al.size();i++)

            {
                Object[] row= new Object[5];
                row[0]=al.get(i).getStudentProfile().getPerson().getPersonId();
                row[1]=al.get(i).getPromotions();
                row[2]=al.get(i).getSalaryRange();
                row[3]=al.get(i).getGradutationYear();
                row[4]=al.get(i).getPosition();
                model.addRow(row);
            } 

        }
    }//GEN-LAST:event_AlmnDptComboBoxActionPerformed

    private void AyDptComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AyDptComboBoxActionPerformed
        // TODO add your handling code here:
        AlmnLstPnl.setVisible(false);
        StdLstPnl.setVisible(false);
        CrLstPnl.setVisible(false);
        AyFcRkPnl.setVisible(false);
        AyCrRkPnl.setVisible(false);
        FcRkLbl.setVisible(false);
        CrRkLbl.setVisible(false);
        CrScMtrxValLbl.setVisible(false);
        CrScMtrxLbl.setVisible(false);
        

        String selval = AyDptComboBox.getSelectedItem().toString();
        

        if(selval.equals("Information Systems"))
        {
            AyFcRkPnl.setVisible(true);
            AyCrRkPnl.setVisible(true);
            FcRkLbl.setVisible(true);
            CrRkLbl.setVisible(true);
            CrScMtrxValLbl.setVisible(true);
            CrScMtrxLbl.setVisible(true);
            
            //For Faculty Ranking
            DefaultTableModel model = (DefaultTableModel) AyFkRkTable.getModel();
            model.setRowCount(0);

            ArrayList<FacultyProfile> frk= rankProfessorByDepartment(map.get("Information Systems"));

            for(int i=0;i<frk.size();i++)

            {
                Object[] row= new Object[2];
                row[0]=frk.get(i).getFacultyRatings();
                row[1]=frk.get(i).getPerson().getPersonId();
                model.addRow(row);

            }

            //For Course Ranking
            DefaultTableModel model1 = (DefaultTableModel) AyCrRkTable.getModel();
            model1.setRowCount(0);
            
            ArrayList<Course> rco= rankCourseByDepartment(map.get("Information Systems"));

            for(int i=0;i<rco.size();i++)

            {
                Object[] row= new Object[2];
                row[0]=rco.get(i).getRating();
                row[1]=rco.get(i).getName();
                model1.addRow(row);

            }
            
            Double csm = careerSuccesMetricRank(map.get("Information Systems"));
            System.out.println(csm);
            CrScMtrxValLbl.setText(csm.toString());
            
            //ArrayList<Alumni> al = d.getAlumniDirectory().getAd();
           // CrMtrxTxtFld.setText(careerSuccesMetricRank);
            
        }
        if(selval.equals("Computer Science"))
        {

            AyFcRkPnl.setVisible(true);
            AyCrRkPnl.setVisible(true);
            FcRkLbl.setVisible(true);
            CrRkLbl.setVisible(true);
            CrScMtrxValLbl.setVisible(true);
            CrScMtrxLbl.setVisible(true);
            
            //For Faculty Ranking
            
            DefaultTableModel model = (DefaultTableModel) AyFkRkTable.getModel();
            model.setRowCount(0);
            
            ArrayList<FacultyProfile> frk= rankProfessorByDepartment(map.get("Computer Science"));
            for(int i=0;i<frk.size();i++)

            {
                Object[] row= new Object[2];
                row[0]=frk.get(i).getFacultyRatings();
                row[1]=frk.get(i).getPerson().getPersonId();
                model.addRow(row);

            }
            
            //For Course Ranking
            DefaultTableModel model1 = (DefaultTableModel) AyCrRkTable.getModel();
            model1.setRowCount(0);
            
            ArrayList<Course> rco= rankCourseByDepartment(map.get("Computer Science"));

            for(int i=0;i<rco.size();i++)

            {
                Object[] row= new Object[2];
                row[0]=rco.get(i).getRating();
                row[1]=rco.get(i).getName();
                model1.addRow(row);

            }
        }
    }//GEN-LAST:event_AyDptComboBoxActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProf;
    private javax.swing.JComboBox<String> AddProfDeptcb1;
    private javax.swing.JTextField AddProfIdTxt;
    private javax.swing.JPanel AddProfPanel;
    private javax.swing.JComboBox<String> AddProfcoucom;
    private javax.swing.JTextField AddProfnameTxt;
    private javax.swing.JComboBox<String> AddStuDeptcb;
    private javax.swing.JLabel AddStuIdLbl;
    private javax.swing.JLabel AddStuIdLbl1;
    private javax.swing.JButton AddStudent;
    private javax.swing.JTextField AddstuIdTxt;
    private javax.swing.JLabel AddstuNameLbl;
    private javax.swing.JLabel AddstuNameLbl1;
    private javax.swing.JLabel AddstucouLbl;
    private javax.swing.JLabel AddstucouLbl1;
    private javax.swing.JComboBox<String> Addstucoucom;
    private javax.swing.JLabel AddstudeptLbl;
    private javax.swing.JLabel AddstudeptLbl1;
    private javax.swing.JTextField AddstunameTxt;
    private javax.swing.JPanel Addstupanel;
    private javax.swing.JComboBox<String> AlmnDptComboBox;
    private javax.swing.JLabel AlmnLstDeptLbl;
    private javax.swing.JPanel AlmnLstPnl;
    private javax.swing.JScrollPane AlmnNameScrPnl;
    private javax.swing.JTable AlmnNameTable;
    private javax.swing.JPanel AyCrRkPnl;
    private javax.swing.JScrollPane AyCrRkScrlPnl;
    private javax.swing.JTable AyCrRkTable;
    private javax.swing.JComboBox<String> AyDptComboBox;
    private javax.swing.JPanel AyFcRkPnl;
    private javax.swing.JScrollPane AyFkRkScrlPnl;
    private javax.swing.JTable AyFkRkTable;
    private javax.swing.JLabel AyLstDeptLbl;
    private javax.swing.JComboBox<String> CrDptComboBox;
    private javax.swing.JLabel CrLstDeptLbl;
    private javax.swing.JPanel CrLstPnl;
    private javax.swing.JScrollPane CrNameScrPnl;
    private javax.swing.JTable CrNameTable;
    private javax.swing.JLabel CrRkLbl;
    private javax.swing.JLabel CrScMtrxLbl;
    private javax.swing.JLabel CrScMtrxValLbl;
    private javax.swing.JLabel FcRkLbl;
    private javax.swing.JTabbedPane InUnvTabPane;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPanel PasswordLowerPanel;
    private javax.swing.JPanel ShAlmn;
    private javax.swing.JPanel ShAyPnl;
    private javax.swing.JPanel ShStdPnl;
    private javax.swing.JPanel ShwCrPnl;
    private javax.swing.JComboBox<String> StdDptComboBox;
    private javax.swing.JLabel StdLstDeptLbl;
    private javax.swing.JPanel StdLstPnl;
    private javax.swing.JScrollPane StdNameScrPnl;
    private javax.swing.JTable StdNameTable;
    private javax.swing.JPanel StudentLoginPanel;
    private javax.swing.JPanel UnvTbPane;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JPanel UsernameLowerPanel;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
