/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI;
import TestData.TestData;
import helper.Helper;
import info5100.university.example.CourseSchedule.CourseOffer;
import info5100.university.example.Department.Department;
import info5100.university.example.Department.DepartmentDirectory;
import info5100.university.example.Info5001UniversityExample;
import info5100.university.example.Persona.StudentProfile;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shreyascr
 */
public class univAdmin extends javax.swing.JPanel {
     HashMap<String, Department> map = new HashMap();
            TestData testData = TestData.getInstance();
            DepartmentDirectory department = testData.getDd();
            ArrayList<Department> departmentlist = department.getDd();
            HashMap<String, CourseOffer> coursemap = new HashMap();
            String depName;
            String depNameProf;

    /** Creates new form univAdmin */
    public univAdmin() {
        initComponents();
        testData.test2();
         UnvTbPane.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        StudentLoginPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        UsernameTextField = new javax.swing.JTextField();
        UsernameLabel = new javax.swing.JLabel();
        PasswordLowerPanel = new javax.swing.JPanel();
        PasswordField = new javax.swing.JPasswordField();
        UsernameLowerPanel = new javax.swing.JPanel();
        LoginButton = new javax.swing.JButton();
        UnvTbPane = new javax.swing.JPanel();
        InUnvTabPane = new javax.swing.JTabbedPane();
        ShwCrPnl = new javax.swing.JPanel();
        CrLstDeptLbl = new javax.swing.JLabel();
        CrDptComboBox = new javax.swing.JComboBox<>();
        CrLstPnl = new javax.swing.JPanel();
        CrNameScrPnl = new javax.swing.JScrollPane();
        CrNameTable = new javax.swing.JTable();
        ShStdPnl = new javax.swing.JPanel();
        StdLstDeptLbl = new javax.swing.JLabel();
        StdDptComboBox = new javax.swing.JComboBox<>();
        StdLstPnl = new javax.swing.JPanel();
        StdNameScrPnl = new javax.swing.JScrollPane();
        StdNameTable = new javax.swing.JTable();
        Addstupanel = new javax.swing.JPanel();
        AddstudeptLbl = new javax.swing.JLabel();
        AddstucouLbl = new javax.swing.JLabel();
        AddstuNameLbl = new javax.swing.JLabel();
        AddStuIdLbl = new javax.swing.JLabel();
        AddStuDeptcb = new javax.swing.JComboBox<>();
        Addstucoucom = new javax.swing.JComboBox<>();
        AddstunameTxt = new javax.swing.JTextField();
        AddstuIdTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        AddStudent = new javax.swing.JButton();
        AddProfPanel = new javax.swing.JPanel();
        AddstudeptLbl1 = new javax.swing.JLabel();
        AddstucouLbl1 = new javax.swing.JLabel();
        AddstuNameLbl1 = new javax.swing.JLabel();
        AddStuIdLbl1 = new javax.swing.JLabel();
        AddProfDeptcb1 = new javax.swing.JComboBox<>();
        AddProfcoucom = new javax.swing.JComboBox<>();
        AddProfnameTxt = new javax.swing.JTextField();
        AddProfIdTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        AddProf = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(29, 44, 64));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 400));

        StudentLoginPanel.setBackground(new java.awt.Color(23, 35, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMIN LOG IN");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout StudentLoginPanelLayout = new javax.swing.GroupLayout(StudentLoginPanel);
        StudentLoginPanel.setLayout(StudentLoginPanelLayout);
        StudentLoginPanelLayout.setHorizontalGroup(
            StudentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        StudentLoginPanelLayout.setVerticalGroup(
            StudentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        PasswordLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(153, 153, 153));
        PasswordLabel.setText("PASSWORD:");

        UsernameTextField.setBackground(new java.awt.Color(44, 63, 87));
        UsernameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UsernameTextField.setForeground(new java.awt.Color(153, 153, 153));
        UsernameTextField.setBorder(null);
        UsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextFieldActionPerformed(evt);
            }
        });

        UsernameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UsernameLabel.setForeground(new java.awt.Color(153, 153, 153));
        UsernameLabel.setText("USERNAME: ");

        PasswordLowerPanel.setBackground(new java.awt.Color(255, 153, 153));
        PasswordLowerPanel.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout PasswordLowerPanelLayout = new javax.swing.GroupLayout(PasswordLowerPanel);
        PasswordLowerPanel.setLayout(PasswordLowerPanelLayout);
        PasswordLowerPanelLayout.setHorizontalGroup(
            PasswordLowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PasswordLowerPanelLayout.setVerticalGroup(
            PasswordLowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        PasswordField.setBackground(new java.awt.Color(44, 63, 87));
        PasswordField.setBorder(null);
        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });

        UsernameLowerPanel.setBackground(new java.awt.Color(255, 153, 153));
        UsernameLowerPanel.setForeground(new java.awt.Color(255, 153, 153));
        UsernameLowerPanel.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout UsernameLowerPanelLayout = new javax.swing.GroupLayout(UsernameLowerPanel);
        UsernameLowerPanel.setLayout(UsernameLowerPanelLayout);
        UsernameLowerPanelLayout.setHorizontalGroup(
            UsernameLowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        UsernameLowerPanelLayout.setVerticalGroup(
            UsernameLowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        LoginButton.setBackground(new java.awt.Color(44, 63, 87));
        LoginButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(153, 153, 153));
        LoginButton.setText("LOGIN");
        LoginButton.setBorder(null);
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StudentLoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(PasswordLowerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(PasswordField)
                    .addComponent(UsernameLowerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(UsernameTextField)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(PasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(UsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 41, Short.MAX_VALUE)))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(StudentLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(UsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(UsernameLowerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(PasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PasswordLowerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        CrLstDeptLbl.setText("Select Department");

        CrDptComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Option" }));
        CrDptComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrDptComboBoxActionPerformed(evt);
            }
        });

        CrNameTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Course Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CrNameScrPnl.setViewportView(CrNameTable);

        javax.swing.GroupLayout CrLstPnlLayout = new javax.swing.GroupLayout(CrLstPnl);
        CrLstPnl.setLayout(CrLstPnlLayout);
        CrLstPnlLayout.setHorizontalGroup(
            CrLstPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrLstPnlLayout.createSequentialGroup()
                .addComponent(CrNameScrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        CrLstPnlLayout.setVerticalGroup(
            CrLstPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrLstPnlLayout.createSequentialGroup()
                .addComponent(CrNameScrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ShwCrPnlLayout = new javax.swing.GroupLayout(ShwCrPnl);
        ShwCrPnl.setLayout(ShwCrPnlLayout);
        ShwCrPnlLayout.setHorizontalGroup(
            ShwCrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShwCrPnlLayout.createSequentialGroup()
                .addGroup(ShwCrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ShwCrPnlLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(CrLstDeptLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CrDptComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ShwCrPnlLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(CrLstPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        ShwCrPnlLayout.setVerticalGroup(
            ShwCrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShwCrPnlLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(ShwCrPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CrLstDeptLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CrDptComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(CrLstPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        InUnvTabPane.addTab("Course List", ShwCrPnl);

        StdLstDeptLbl.setText("Select Department");

        StdDptComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Option" }));
        StdDptComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StdDptComboBoxActionPerformed(evt);
            }
        });

        StdNameTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Student Name", "Stduent GPA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        StdNameScrPnl.setViewportView(StdNameTable);

        javax.swing.GroupLayout StdLstPnlLayout = new javax.swing.GroupLayout(StdLstPnl);
        StdLstPnl.setLayout(StdLstPnlLayout);
        StdLstPnlLayout.setHorizontalGroup(
            StdLstPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StdLstPnlLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(StdNameScrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        StdLstPnlLayout.setVerticalGroup(
            StdLstPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StdLstPnlLayout.createSequentialGroup()
                .addComponent(StdNameScrPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ShStdPnlLayout = new javax.swing.GroupLayout(ShStdPnl);
        ShStdPnl.setLayout(ShStdPnlLayout);
        ShStdPnlLayout.setHorizontalGroup(
            ShStdPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShStdPnlLayout.createSequentialGroup()
                .addGroup(ShStdPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ShStdPnlLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(StdLstDeptLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StdDptComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ShStdPnlLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(StdLstPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        ShStdPnlLayout.setVerticalGroup(
            ShStdPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShStdPnlLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(ShStdPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StdLstDeptLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StdDptComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(StdLstPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        InUnvTabPane.addTab("Student List", ShStdPnl);

        AddstudeptLbl.setText("Department:");

        AddstucouLbl.setText("Course:");

        AddstuNameLbl.setText("Name:");

        AddStuIdLbl.setText("Id:");

        AddStuDeptcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department" }));
        AddStuDeptcb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AddStuDeptcbMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddStuDeptcbMouseClicked(evt);
            }
        });
        AddStuDeptcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStuDeptcbActionPerformed(evt);
            }
        });

        Addstucoucom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Course" }));
        Addstucoucom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddstucoucomActionPerformed(evt);
            }
        });

        AddstunameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddstunameTxtActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Add Student");

        AddStudent.setText("Add");
        AddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddstupanelLayout = new javax.swing.GroupLayout(Addstupanel);
        Addstupanel.setLayout(AddstupanelLayout);
        AddstupanelLayout.setHorizontalGroup(
            AddstupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddstupanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddstupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddstuNameLbl)
                    .addComponent(AddStuIdLbl)
                    .addComponent(AddstudeptLbl)
                    .addComponent(AddstucouLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addGroup(AddstupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddstupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Addstucoucom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddStuDeptcb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(AddstuIdTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(AddstunameTxt, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(83, 83, 83))
            .addGroup(AddstupanelLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(AddstupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddStudent))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddstupanelLayout.setVerticalGroup(
            AddstupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddstupanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addGap(36, 36, 36)
                .addGroup(AddstupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddstuNameLbl)
                    .addGroup(AddstupanelLayout.createSequentialGroup()
                        .addComponent(AddstunameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AddstupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddStuIdLbl)
                            .addComponent(AddstuIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addGroup(AddstupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddstudeptLbl)
                    .addComponent(AddStuDeptcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(AddstupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddstucouLbl)
                    .addComponent(Addstucoucom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AddStudent)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        InUnvTabPane.addTab("Add Student", Addstupanel);

        AddstudeptLbl1.setText("Department:");

        AddstucouLbl1.setText("Course:");

        AddstuNameLbl1.setText("Name:");

        AddStuIdLbl1.setText("Id:");

        AddProfDeptcb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department" }));
        AddProfDeptcb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AddProfDeptcb1MousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddProfDeptcb1MouseClicked(evt);
            }
        });
        AddProfDeptcb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProfDeptcb1ActionPerformed(evt);
            }
        });

        AddProfcoucom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Course" }));
        AddProfcoucom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProfcoucomActionPerformed(evt);
            }
        });

        AddProfnameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProfnameTxtActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Add Professor");

        AddProf.setText("Add");
        AddProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddProfPanelLayout = new javax.swing.GroupLayout(AddProfPanel);
        AddProfPanel.setLayout(AddProfPanelLayout);
        AddProfPanelLayout.setHorizontalGroup(
            AddProfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddProfPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddProfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddstuNameLbl1)
                    .addComponent(AddStuIdLbl1)
                    .addComponent(AddstudeptLbl1)
                    .addComponent(AddstucouLbl1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addGroup(AddProfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddProfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(AddProfcoucom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddProfDeptcb1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(AddProfIdTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AddProfnameTxt, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(83, 83, 83))
            .addGroup(AddProfPanelLayout.createSequentialGroup()
                .addGroup(AddProfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddProfPanelLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(AddProf))
                    .addGroup(AddProfPanelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddProfPanelLayout.setVerticalGroup(
            AddProfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddProfPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel6)
                .addGap(31, 31, 31)
                .addGroup(AddProfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddstuNameLbl1)
                    .addGroup(AddProfPanelLayout.createSequentialGroup()
                        .addComponent(AddProfnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AddProfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddStuIdLbl1)
                            .addComponent(AddProfIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addGroup(AddProfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddstudeptLbl1)
                    .addComponent(AddProfDeptcb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(AddProfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddstucouLbl1)
                    .addComponent(AddProfcoucom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AddProf)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        InUnvTabPane.addTab("Add Professor", AddProfPanel);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
        );

        InUnvTabPane.addTab("tab5", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
        );

        InUnvTabPane.addTab("tab6", jPanel6);

        javax.swing.GroupLayout UnvTbPaneLayout = new javax.swing.GroupLayout(UnvTbPane);
        UnvTbPane.setLayout(UnvTbPaneLayout);
        UnvTbPaneLayout.setHorizontalGroup(
            UnvTbPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InUnvTabPane)
        );
        UnvTbPaneLayout.setVerticalGroup(
            UnvTbPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InUnvTabPane, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(UnvTbPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(UnvTbPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextFieldActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        jPanel1.setVisible(false);
        UnvTbPane.setVisible(true);
           
            CrLstPnl.setVisible(false);
            StdLstPnl.setVisible(false);
            ArrayList<Department> departmentlist = department.getDd();
            
            for(Department d : departmentlist){
               
                map.put(d.getName(), d);
            }

            for (String name : map.keySet())  
                   CrDptComboBox.addItem(name);
            for (String name : map.keySet()) 
                StdDptComboBox.addItem(name);
            for (String name : map.keySet())  
                   AddStuDeptcb.addItem(name);
            for (String name : map.keySet())  
                   AddProfDeptcb1.addItem(name);
        
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void CrDptComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrDptComboBoxActionPerformed
        // TODO add your handling code here:

        CrLstPnl.setVisible(false);
        StdLstPnl.setVisible(false);
        String selval = CrDptComboBox.getSelectedItem().toString();
        //jTextField1.setText(selval);

        if(selval.equals("Information Systems"))
        {
            CrLstPnl.setVisible(true);
            DefaultTableModel model = (DefaultTableModel) CrNameTable.getModel();
            model.setRowCount(0);

            System.out.println("Test "+ map.get("Information Systems"));
            List<CourseOffer> co = getCourseOfferedByDepartment(map.get("Information Systems"));

            for(int i=0;i<co.size();i++)

            {
                Object[] row= new Object[1];
                row[0]=co.get(i).getCourse().getName();
                model.addRow(row);

            }
        }
        if(selval.equals("Computer Science"))
        {
            CrLstPnl.setVisible(true);
            DefaultTableModel model = (DefaultTableModel) CrNameTable.getModel();
            model.setRowCount(0);

            System.out.println("Test "+ map.get("Computer Science"));
            List<CourseOffer> co = getCourseOfferedByDepartment(map.get("Computer Science"));
            for(int i=0;i<co.size();i++)
            //for(CourseOffer c: co)
            {
                Object[] row= new Object[1];
                row[0]=co.get(i).getCourse().getName();
                model.addRow(row);

            }
        }

    }//GEN-LAST:event_CrDptComboBoxActionPerformed

        public void getDepartmentList(){
         
//        ArrayList<Department> departmentlist = department.getDd();
        for(Department d : departmentlist)
        {
            System.out.println(d.getName());
//            Helper helper = new Helper();
//            List<Course> course = helper.getCourseOffer(d, "Fall2020");
//            for(Course c : course)
//            {
//                System.out.println(c.getName());
//            }
//            List<Person> list = helper.getStudent(d);
//            for(Person p : list)
//            {
//                System.out.println(p.getPersonId());
//            }
            
           
           getCourseOfferedByDepartment(d); 
    }
    
        
        
//        String d1 ="Information Systems";
//        String course ="app eng";
//       
//        for(Department d : departmentlist)
//        {
//            //System.out.println(d.getName());
//            Helper helper = new Helper();
//            List<CourseOffer> course1 = helper.getCourseOfferList(d, "Fall2020");
//            for(CourseOffer c : course1)
//            {
//                    if(c.getCourse().getName().equals(course))
//                    {
//                        helper.addStudent(d, "test", "1234", "Fall2020",c );
//                        
//                    }
//            }
//        }
//        for(Department d : departmentlist)
//        {
//            System.out.println(d.getName());
//            Helper helper = new Helper();
//            List<Course> course2 = helper.getCourseOffer(d, "Fall2020");
//            for(Course c : course2)
//            {
//                System.out.println(c.getName());
//            }
//            List<Person> list = helper.getStudent(d);
//            for(Person p : list)
//            {
//                System.out.println(p.getPersonId());
//            }
//        }
            
            
            
        
        
      //  System.out.println("DD "+ uni.getDd().toString());
//        ArrayList<DepartmentDirectory> d = uni.getDd();
        
    }                                        


    public List<StudentProfile> getStudentsByDepartmentName(Department dpt){
            Helper helper = new Helper();
            List<StudentProfile> p = helper.getStudent(dpt);
//            for(Course c : course)
//            {
//                System.out.println(c.getName());
//            }
//            List<Person> list = helper.getStudent(d);
//            for(Person p : list)
//            {
//                System.out.println(p.getPersonId());
//            }
          //  System.out.println("PP "+ p.get(0).getPersonId());
            return p;
    }
    
    public List<CourseOffer> getCourseOfferedByDepartment(Department d){
        return new Helper().getCourseOfferList(d, "Fall2020");
    }
    
    public void addStudent(Department d, String sname, String sid, String sem, CourseOffer co){
        
        new Helper().addStudent(d, sname, sid, sem, co);
        
        
    }
   // System.out.println("Std"+new Helper().addStudent(d, "MM", "101", "2", co));
    
    public void addProf(Department d, String profName, String pid, String sem, CourseOffer co){
        
        new Helper().addProfessor(d, profName, pid, sem, co);
    }
    
    private void StdDptComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StdDptComboBoxActionPerformed
        // TODO add your handling code here:

        StdLstPnl.setVisible(false);

        String selval = StdDptComboBox.getSelectedItem().toString();
        //jTextField1.setText(selval);

        if(selval.equals("Information Systems"))
        {
            StdLstPnl.setVisible(true);
            DefaultTableModel model = (DefaultTableModel) StdNameTable.getModel();
            model.setRowCount(0);

            //System.out.println("Test "+ map.get("Information Systems"));
            //List<CourseOffer> co = getCourseOfferedByDepartment(map.get("Information Systems"));
            List<StudentProfile> p = getStudentsByDepartmentName(map.get("Information Systems"));
            for(int i=0;i<p.size();i++)
            //for(CourseOffer c: co)
            {
                Object[] row= new Object[2];
                //row[0]=co.get(i).getCourse().getName().toString();
                row[0]=p.get(i).getPerson().getPersonId();
                row[1]=p.get(i).getGpa();
                model.addRow(row);
            }

        }

        if(selval.equals("Computer Science"))
        {
            StdLstPnl.setVisible(true);
            DefaultTableModel model = (DefaultTableModel) StdNameTable.getModel();
            model.setRowCount(0);

            System.out.println("Test "+ map.get("Computer Science"));
            //List<CourseOffer> co = getCourseOfferedByDepartment(map.get("Computer Science"));
            List<StudentProfile> p = getStudentsByDepartmentName(map.get("Computer Science"));
            for(int i=0;i<p.size();i++)
            //for(CourseOffer c: co)
            {
                Object[] row= new Object[2];

                row[0]=p.get(i).getPerson().getPersonId();
                row[1]=p.get(i).getGpa();
                model.addRow(row);

            }
        }
    }//GEN-LAST:event_StdDptComboBoxActionPerformed

    private void AddStuDeptcbMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddStuDeptcbMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddStuDeptcbMousePressed

    private void AddStuDeptcbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddStuDeptcbMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AddStuDeptcbMouseClicked

    private void AddStuDeptcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStuDeptcbActionPerformed
        // TODO add your handling code here:
        //getDepartmentList();
        depName = AddStuDeptcb.getSelectedItem().toString();
        System.out.println(depName);
        AddstucoucomActionPerformed(evt);
        //                    List<CourseOffer> depname = getCourseOfferedByDepartment(map.get(depName));
        //        for(CourseOffer co : depname){
            //                        coursemap.put(co.getCourseNumber(), co);
            //              }
        //            for (String couname : coursemap.keySet())
        //                   Addstucoucom.addItem(couname);
    }//GEN-LAST:event_AddStuDeptcbActionPerformed

    private void AddstucoucomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddstucoucomActionPerformed
        // TODO add your handling code here:
        //String courseName =
        List<CourseOffer> depname = getCourseOfferedByDepartment(map.get(depName));
        for(CourseOffer co : depname){
            coursemap.put(co.getCourseNumber(), co);
        }
        for (String couname : coursemap.keySet())
        Addstucoucom.addItem(couname);
    }//GEN-LAST:event_AddstucoucomActionPerformed

    private void AddstunameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddstunameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddstunameTxtActionPerformed

    private void AddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudentActionPerformed
        // TODO add your handling code here:
        depName = AddStuDeptcb.getSelectedItem().toString();
        String stuname=AddstunameTxt.getText();
        String stid = AddstuIdTxt.getText();
        String coursename = Addstucoucom.getSelectedItem().toString();
        addStudent(map.get(depName), stuname, stid, "Fall2020 ", coursemap.get(coursename));
        JOptionPane.showMessageDialog(this,"Student Added");
        InUnvTabPane.setSelectedComponent(this.ShStdPnl);
    }//GEN-LAST:event_AddStudentActionPerformed

    private void AddProfDeptcb1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddProfDeptcb1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddProfDeptcb1MousePressed

    private void AddProfDeptcb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddProfDeptcb1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AddProfDeptcb1MouseClicked

    private void AddProfDeptcb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProfDeptcb1ActionPerformed
        // TODO add your handling code here:
        depNameProf = AddProfDeptcb1.getSelectedItem().toString();
        System.out.println(depNameProf);
        AddProfcoucomActionPerformed(evt);
    }//GEN-LAST:event_AddProfDeptcb1ActionPerformed

    private void AddProfcoucomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProfcoucomActionPerformed
        // TODO add your handling code here:
        List<CourseOffer> depname = getCourseOfferedByDepartment(map.get(depNameProf));
        for(CourseOffer co : depname){
            coursemap.put(co.getCourseNumber(), co);
        }
        for (String couname : coursemap.keySet())
        AddProfcoucom.addItem(couname);
    }//GEN-LAST:event_AddProfcoucomActionPerformed

    private void AddProfnameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProfnameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddProfnameTxtActionPerformed

    private void AddProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProfActionPerformed
        // TODO add your handling code here:
        String profname=AddProfnameTxt.getText();
        String profid = AddProfIdTxt.getText();
        String coursename = AddProfcoucom.getSelectedItem().toString();
        addProf(map.get(depNameProf), profname, profid, "Fall2020 ", coursemap.get(coursename));
        JOptionPane.showMessageDialog(this,"Professor Added");
    }//GEN-LAST:event_AddProfActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProf;
    private javax.swing.JComboBox<String> AddProfDeptcb1;
    private javax.swing.JTextField AddProfIdTxt;
    private javax.swing.JPanel AddProfPanel;
    private javax.swing.JComboBox<String> AddProfcoucom;
    private javax.swing.JTextField AddProfnameTxt;
    private javax.swing.JComboBox<String> AddStuDeptcb;
    private javax.swing.JLabel AddStuIdLbl;
    private javax.swing.JLabel AddStuIdLbl1;
    private javax.swing.JButton AddStudent;
    private javax.swing.JTextField AddstuIdTxt;
    private javax.swing.JLabel AddstuNameLbl;
    private javax.swing.JLabel AddstuNameLbl1;
    private javax.swing.JLabel AddstucouLbl;
    private javax.swing.JLabel AddstucouLbl1;
    private javax.swing.JComboBox<String> Addstucoucom;
    private javax.swing.JLabel AddstudeptLbl;
    private javax.swing.JLabel AddstudeptLbl1;
    private javax.swing.JTextField AddstunameTxt;
    private javax.swing.JPanel Addstupanel;
    private javax.swing.JComboBox<String> CrDptComboBox;
    private javax.swing.JLabel CrLstDeptLbl;
    private javax.swing.JPanel CrLstPnl;
    private javax.swing.JScrollPane CrNameScrPnl;
    private javax.swing.JTable CrNameTable;
    private javax.swing.JTabbedPane InUnvTabPane;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPanel PasswordLowerPanel;
    private javax.swing.JPanel ShStdPnl;
    private javax.swing.JPanel ShwCrPnl;
    private javax.swing.JComboBox<String> StdDptComboBox;
    private javax.swing.JLabel StdLstDeptLbl;
    private javax.swing.JPanel StdLstPnl;
    private javax.swing.JScrollPane StdNameScrPnl;
    private javax.swing.JTable StdNameTable;
    private javax.swing.JPanel StudentLoginPanel;
    private javax.swing.JPanel UnvTbPane;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JPanel UsernameLowerPanel;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables

}
